version: '3'
services:
  server:
    build: docker/nginx
    container_name: cms_server
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./app/:/usr/share/nginx/html
    depends_on:
      - php-fpm
  php-fpm:
    build: docker/php
    container_name: cms_php
    volumes:
      - ./app/:/usr/share/nginx/html
  database:
    image: mysql:8
    container_name: cms_database
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./.db_data:/var/lib/mysql
