sidebar-main:
  dashboard:
    label: Tableau de bord
    icon: fas fa-columns
    route:
    sub-links:
      stats:
        label: Statistiques
        route:
      customize:
        label: Personnalisez votre site
        route:
  article: 
    label: Articles
    icon: fas fa-newspaper
    route: /test-list
    sub-links:
      list_article:
        label: Liste article
        route: /test-list
      add_article:
        label: Ajouter article
        route: /test-create
  page: 
    label: Pages
    icon: far fa-file
    route:
    sub-links:
      list_page:
        label: Liste page
        route:
      add_page:
        label: Ajouter page
        route:
  user: 
    label: Utilisateurs
    icon: fas fa-users
    route:
        
sidebar-bottom:
  settings:
  label: Paramètres
  icon: fas fa-cog
  route: