/:
  controller: Home
  method: defaultView

/login:
  controller: Home
  method: loginAction

/logout:
  controller: Home
  method: logoutAction

/register:
  controller: Home
  method: registerView

/list-article:
  controller: Home
  method: listArticleView

/save-list-article:
  controller: Home
  method: listArticleAction