/:
  controller: Home
  method: defaultView
  require_auth: True

/dashboard:
  controller: Home
  method: defaultView
  require_auth: True

# installer
/installer-register:
  controller: Installer
  method: installerRegisterView

/installer-db:
  controller: Installer
  method: installerDatabaseView

/installer/load-db:
  controller: Installer
  method: loadDatabaseAction

/installer/test:
  controller: Installer
  method: testView

/installer/register-save:
  controller: Installer
  method: registerAction

# Authentification
/login:
  controller: Auth
  method: loginView

/login-send:
  controller: Auth
  method: loginAction

/logout:
  controller: Auth
  method: logoutAction

/recover-password:
  controller: Auth
  method: passwordRecoveryView

/recover-password-send:
  controller: Auth
  method: passwordRecoveryAction

/reset-password:
  controller: Auth
  method: passwordResetView

/reset-password-send:
  controller: Auth
  method: passwordResetAction

/auth/test:
  controller: Auth
  method: test

# User management
/users:
  controller: User
  method: listView
  require_auth: True

/users-save:
  controller: User
  method: listAction
  require_auth: True

/new-user:
  controller: User
  method: createView
  require_auth: True

/new-user-save:
  controller: User
  method: createAction
  require_auth: True

/user:
  controller: User
  method: userView
  require_auth: True

/user-save:
  controller: User
  method: userAction
  require_auth: True

/delete-user:
  controller: User
  method: deleteAction
  require_auth: True
