/:
  controller: Home
  method: defaultView
  require_auth: True

/dashboard:
  controller: Home
  method: defaultView
  require_auth: True

# installer
/installer-db:
  controller: Installer
  method: installerDatabaseView

/installer-db-save:
  controller: Installer
  method: loadDatabaseAction

/installer-register:
  controller: Installer
  method: installerRegisterView

/installer-register-save:
  controller: Installer
  method: registerAction

# Authentification
/login:
  controller: User
  method: loginView

/login-send:
  controller: User
  method: loginAction

/logout:
  controller: User
  method: logoutAction

/recover-password:
  controller: User
  method: passwordRecoveryView

/recover-password-send:
  controller: User
  method: passwordRecoveryAction

/reset-password:
  controller: User
  method: passwordResetView

/reset-password-send:
  controller: User
  method: passwordResetAction

# User management
/users:
  controller: User
  method: listView
  require_auth: True

/users-save:
  controller: User
  method: listAction
  require_auth: True

/new-user:
  controller: User
  method: createView
  require_auth: True

/new-user-save:
  controller: User
  method: createAction
  require_auth: True

/user:
  controller: User
  method: userView
  require_auth: True

/user-save:
  controller: User
  method: userAction
  require_auth: True

/delete-user:
  controller: User
  method: deleteAction
  require_auth: True

/confirm-account:
  controller: User
  method: confirmAccountView