/:
  controller: Home
  method: dashboardView
  title: Tableau de bord
  require_auth: True
  display_back_office: True

/dashboard:
  controller: Home
  method: dashboardView
  title: Tableau de bord
  require_auth: True
  display_back_office: True

# installer
/installer:
  controller: Installer
  method: installerView

/installer-db-save:
  controller: Installer
  method: loadDatabaseAction

/installer-register-save:
  controller: Installer
  method: registerAction

# Authentication
/login:
  controller: Auth
  method: loginView
  title: Connexion

/login-send:
  controller: Auth
  method: loginAction

/logout:
  controller: Auth
  method: logoutAction

/recover-password:
  controller: Auth
  method: passwordRecoveryView
  title: Mot de passe oublié

/recover-password-send:
  controller: Auth
  method: passwordRecoveryAction

/update-password:
  controller: Auth
  method: passwordUpdateView

/update-password-send:
  controller: Auth
  method: passwordUpdateAction

/confirm-account:
  controller: Auth
  method: confirmAccountView
  title: Confirmation du compte

# User management
/users:
  controller: User
  method: listView
  title: Liste des utilisateurs
  require_auth: True
  display_back_office: True

/users-save:
  controller: User
  method: listAction
  require_auth: True

/new-user:
  controller: User
  method: createView
  title: Ajouter un utilisateur
  require_auth: True
  display_back_office: True

/new-user-save:
  controller: User
  method: createAction
  require_auth: True

/user:
  controller: User
  method: userView
  title: Profil
  require_auth: True
  display_back_office: True

/user-save:
  controller: User
  method: userAction
  require_auth: True

/delete-user:
  controller: User
  method: deleteAction
  require_auth: True

/user-reconfirmation:
  controller: User
  method: reconfirmationAction
  require_auth: True




# Page management
/pages:
  controller: Page
  method: listView
  title: Liste des pages
  require_auth: True
  display_back_office: True

/pages-save:
  controller: Page
  method: listAction
  require_auth: True

/new-page:
  controller: Page
  method: createView
  title: Ajouter une page
  require_auth: True
  display_back_office: True

/new-page-save:
  controller: Page
  method: createAction
  require_auth: True

/page:
  controller: Page
  method: pageView
  title: Page
  require_auth: True
  display_back_office: True

/page-save:
  controller: Page
  method: pageAction
  require_auth: True

/delete-page:
  controller: Page
  method: deleteAction
  require_auth: True

/page-link-list:
  controller: Page
  method: getPageLinkList


# Role management
/role:
  controller: Role
  method: roleView
  title: Gestion des rôles
  require_auth: True
  display_back_office: True

/role-tab:
  controller: Role
  method: roleTabView
  require_auth: True

/role-save:
  controller: Role
  method: roleAction
  require_auth: True


# Webpage editor (appearance)
/menu:
  controller: Appearance
  method: menuView
  title: Liste des menus
  require_auth: True
  display_back_office: True

/menu-tab:
  controller: Appearance
  method: menuTabView
  title: Modifier un menu
  require_auth: True

/menu-save:
  controller: Appearance
  method: menuAction
  require_auth: True

/delete-menu:
  controller: Appearance
  method: deleteMenuAction
  require_auth: True

/customization:
  controller: Appearance
  method: customizationView
  title: Personnalisation
  require_auth: True
  display_back_office: True

/customization-save:
  controller: Appearance
  method: customizationAction
  require_auth: True


# Settings
/settings:
  controller: Settings
  method: settingsView
  title: Paramètres
  require_auth: True
  display_back_office: True

/settings-general-save:
  controller: Settings
  method: settingsGeneralAction
  require_auth: True

/settings-mail-save:
  controller: Settings
  method: settingsMailAction
  require_auth: True

/settings-page-save:
  controller: Settings
  method: settingsPageAction
  require_auth: True

# Newsletter
/newsletters:
  controller: Newsletter
  method: listView
  title: Newsletter
  require_auth: True
  display_back_office: True

/new-newsletter:
  controller: Newsletter
  method: createView
  title: Newsletter
  require_auth: True
  display_back_office: True

/new-newsletter-save:
  controller: Newsletter
  method: createAction
  require_auth: True

/newsletter:
  controller: Newsletter
  method: newsletterView
  title: Newsletter
  require_auth: True
  display_back_office: True

/newsletter-save:
  controller: Newsletter
  method: newsletterAction
  require_auth: True

/delete-newsletter:
  controller: Newsletter
  method: deleteAction
  require_auth: True

/unsubscribe:
  controller: Newsletter
  method: unsubscribeView