/:
  controller: Home
  method: defaultView
  require_auth: True

/dashboard:
  controller: Home
  method: defaultView
  require_auth: True

# installer
/installer-register:
  controller: Installer
  method: installerRegisterView

/installer-db:
  controller: Installer
  method: installerDatabaseView

/installer/load-db:
  controller: Installer
  method: loadDatabaseAction

/installer/test:
  controller: Installer
  method: testView

/installer/register-save:
  controller: Installer
  method: registerAction

# Authentification
/login:
  controller: Auth
  method: loginView

/login-send:
  controller: Auth
  method: loginAction

/logout:
  controller: Auth
  method: logoutAction

/recover-password:
  controller: Auth
  method: passwordRecoveryView

/recover-password-send:
  controller: Auth
  method: passwordRecoveryAction

/reset-password:
  controller: Auth
  method: passwordResetView

/reset-password-send:
  controller: Auth
  method: passwordResetAction

/auth/test:
  controller: Auth
  method: test