/:
  controller: Home
  method: defaultView
  title: Tableau de bord
  require_auth: True

/dashboard:
  controller: Home
  method: defaultView
  title: Tableau de bord
  require_auth: True

# installer
/installer-db:
  controller: Installer
  method: installerDatabaseView
  title: Configuration de la base de données

/installer-db-save:
  controller: Installer
  method: loadDatabaseAction

/installer-register:
  controller: Installer
  method: installerRegisterView
  title: Inscription

/installer-register-save:
  controller: Installer
  method: registerAction

# Authentification
/login:
  controller: User
  method: loginView
  title: Connexion

/login-send:
  controller: User
  method: loginAction

/logout:
  controller: User
  method: logoutAction

/recover-password:
  controller: User
  method: passwordRecoveryView
  title: Mot de passe oublié

/recover-password-send:
  controller: User
  method: passwordRecoveryAction

/reset-password:
  controller: User
  method: passwordResetView
  title: Réinitialisation du mot de passe

/reset-password-send:
  controller: User
  method: passwordResetAction

# User management
/users:
  controller: User
  method: listView
  title: Liste des utilisateurs
  require_auth: True

/users-save:
  controller: User
  method: listAction
  require_auth: True

/new-user:
  controller: User
  method: createView
  title: Ajouter un utilisateur
  require_auth: True

/new-user-save:
  controller: User
  method: createAction
  require_auth: True

/user:
  controller: User
  method: userView
  title: Profil
  require_auth: True

/user-save:
  controller: User
  method: userAction
  require_auth: True

/delete-user:
  controller: User
  method: deleteAction
  require_auth: True

/confirm-account:
  controller: User
  method: confirmAccountView
  title: Confirmation du compte

# Page management
/pages:
  controller: Page
  method: listView
  title: Liste des pages
  require_auth: True

/pages-save:
  controller: Page
  method: listAction
  require_auth: True

/new-page:
  controller: Page
  method: createView
  title: Ajouter une page
  require_auth: True

/new-page-save:
  controller: Page
  method: createAction
  require_auth: True

/page:
  controller: Page
  method: pageView
  title: Page
  require_auth: True

/page-save:
  controller: Page
  method: pageAction
  require_auth: True

/delete-page:
  controller: Page
  method: deleteAction
  require_auth: True

/page-link-list:
  controller: Page
  method: getPageLinkList


# Role management
/roles:
  controller: Role
  method: roleView
  title: Gestion des rôles
  require_auth: True

/role-tab:
  controller: Role
  method: roleTabView
  require_auth: True

/role-save:
  controller: Role
  method: roleAction
  require_auth: True