/:
  controller: Home
  method: defaultView

/dashboard:
  controller: Home
  method: defaultView

/logout:
  controller: Home
  method: logoutAction

/register:
  controller: Home
  method: registerView

# installer

/installer-register:
  controller: Installer
  method: installerRegisterView

/installer-db:
  controller: Installer
  method: installerDatabaseView

/installer/load-db:
  controller: Installer
  method: loadDatabaseAction

/installer/test:
  controller: Installer
  method: testView

/installer/register-save:
  controller: Installer
  method: registerAction

# Login / Logout / Register
/login:
  controller: Auth
  method: loginView

/auth/login:
  controller: Auth
  method: loginAction

/auth/password-recovery:
  controller: Auth
  method: passwordRecoveryView

/auth/logout:
  controller: Auth
  method: logoutAction

/auth/register:
  controller: Auth
  method: registerAction

/auth/test:
  controller: Auth
  method: test