/:
  controller: Home
  method: defaultView

/login:
  controller: Home
  method: loginAction

/logout:
  controller: Home
  method: logoutAction

/register:
  controller: Home
  method: registerView

# installer

/installer-register:
  controller: Installer
  method: installerRegisterView

/installer-db:
  controller: Installer
  method: installerDbView

/installer-load:
  controller: Installer
  method: installerAction

/installer/test:
  controller: Installer
  method: installerAction